### ISSUE TITLE
Captive portal not working on iOS

### ISSUE THREAD

**Issue by syskeyt** [h-enes-simsek/ESP32ChatInCaptivePortal#1]
It works on windows, but not on iOS.

Edit: I found out there is a data limit on captive portals for iOS

**Comment by h-enes-simsek** [comment]
Hello @syskeyt 
Thank you for your attention. Because I don't have an iPhone, I'm unable to control it on iOS.
Can you add more detail, Which part of app was not working? Could you send a message via app? What did you do to solve the problem? Maybe, we can add a note to readme file or fix the problem if we can for future users not to take their times.
